#!/bin/bash

# Railway Environment Variables Setup Script
# This helps you set up Google Ads API credentials on Railway

echo "=========================================="
echo "Railway Environment Variables Setup"
echo "=========================================="
echo ""
echo "You need to set these variables in Railway:"
echo ""
echo "1. Go to your Railway project dashboard"
echo "2. Click on your backend service"
echo "3. Go to the 'Variables' tab"
echo "4. Add these variables:"
echo ""
echo "GOOGLE_ADS_CLIENT_ID"
echo "  Description: OAuth 2.0 Client ID from Google Cloud Console"
echo "  Example: 123456789-abc.apps.googleusercontent.com"
echo ""
echo "GOOGLE_ADS_CLIENT_SECRET"
echo "  Description: OAuth 2.0 Client Secret"
echo "  Example: GOCSPX-xyz123..."
echo ""
echo "GOOGLE_ADS_DEVELOPER_TOKEN"
echo "  Description: Developer token from Google Ads API Center"
echo "  Example: abcd1234..."
echo ""
echo "GOOGLE_ADS_REDIRECT_URI (optional)"
echo "  Description: OAuth callback URL"
echo "  Default: Will use BACKEND_URL + /api/integrations/google-ads/oauth/callback"
echo "  Example: https://growth-copilot-prod-production.up.railway.app/api/integrations/google-ads/oauth/callback"
echo ""
echo "=========================================="
echo "After setting these variables:"
echo "1. Railway will automatically redeploy"
echo "2. Wait for deployment to complete"
echo "3. Test OAuth flow through your app"
echo "=========================================="
echo ""
echo "To verify variables are set, you can use Railway CLI:"
echo "railway variables"
echo ""