"""Initial migration

Revision ID: d995feb98eea
Revises: 
Create Date: 2025-08-30 05:54:04.940326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd995feb98eea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitor_cache',
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.Enum('SAAS', 'ECOMMERCE', 'ENTERPRISE', 'MARKETPLACE', 'AGENCY', 'FINTECH', 'HEALTHTECH', 'EDTECH', 'OTHER', name='industry'), nullable=False),
    sa.Column('last_analyzed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('pricing_model', sa.String(length=100), nullable=True),
    sa.Column('traffic_estimate', sa.Integer(), nullable=True),
    sa.Column('update_frequency', sa.Integer(), nullable=True),
    sa.Column('analysis_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_slug', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_share_slug'), 'conversations', ['share_slug'], unique=True)
    op.create_table('industry_benchmarks',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.Enum('SAAS', 'ECOMMERCE', 'ENTERPRISE', 'MARKETPLACE', 'AGENCY', 'FINTECH', 'HEALTHTECH', 'EDTECH', 'OTHER', name='industry'), nullable=False),
    sa.Column('metric_type', sa.Enum('CONVERSION_RATE', 'FORM_FIELDS', 'PAGE_SPEED', 'MOBILE_SCORE', 'TIME_TO_VALUE', 'TRIAL_LENGTH', 'PRICING_TRANSPARENCY', 'SUPPORT_RESPONSE', name='metrictype'), nullable=False),
    sa.Column('p25_value', sa.Float(), nullable=True),
    sa.Column('p50_value', sa.Float(), nullable=True),
    sa.Column('p75_value', sa.Float(), nullable=True),
    sa.Column('p90_value', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_benchmarks_industry'), 'industry_benchmarks', ['industry'], unique=False)
    op.create_table('analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.Enum('SAAS', 'ECOMMERCE', 'ENTERPRISE', 'MARKETPLACE', 'AGENCY', 'FINTECH', 'HEALTHTECH', 'EDTECH', 'OTHER', name='industry'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'COMPLETED', 'FAILED', 'PARTIAL', name='analysisstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('issues_found', sa.JSON(), nullable=True),
    sa.Column('revenue_impact', sa.Float(), nullable=True),
    sa.Column('quick_wins', sa.JSON(), nullable=True),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('conversion_score', sa.Integer(), nullable=True),
    sa.Column('mobile_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_domain'), 'analyses', ['domain'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'ANALYSIS_UPDATE', 'RICH_CARD', 'ERROR', name='messagetype'), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_index(op.f('ix_analyses_domain'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_industry_benchmarks_industry'), table_name='industry_benchmarks')
    op.drop_table('industry_benchmarks')
    op.drop_index(op.f('ix_conversations_share_slug'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('competitor_cache')
    # ### end Alembic commands ###
